apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: crm-web-hpa
spec:
  minReplicas: 3
  maxReplicas: 20
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: crm-celery-hpa
spec:
  minReplicas: 3
  maxReplicas: 15
