name: mobile_app
description: "Client Portal Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.0
  
  # API
  http: ^1.1.0
  shared_preferences: ^2.2.0
  
  # Utilities
  intl: ^0.18.0
  
  # UI
  google_fonts: ^5.1.0
  flutter_animate: ^4.2.0
  signature: ^5.4.0
  flutter_widget_from_html_core: 0.10.0
  qr_flutter: ^4.1.0
  
  # QR Scanner
  mobile_scanner: ^5.1.1
  
  # Video Player & Sharing
  url_launcher: ^6.2.0
  share_plus: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
