apiVersion: v1
kind: ConfigMap
metadata:
  name: crm-config
  namespace: crm
data:
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  POSTGRES_DB: "crm_db"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
