apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crm

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - pvc.yaml
  - postgres.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: crm
  app.kubernetes.io/managed-by: kustomize
