apiVersion: v1
kind: ServiceAccount
metadata:
  name: crm-service-account
  namespace: crm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crm-role
  namespace: crm
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crm-role-binding
  namespace: crm
subjects:
  - kind: ServiceAccount
    name: crm-service-account
    namespace: crm
roleRef:
  kind: Role
  name: crm-role
  apiGroup: rbac.authorization.k8s.io
