apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crm-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml

configMapGenerator:
  - name: crm-config
    behavior: merge
    literals:
      - DJANGO_ENV=staging
      - DEBUG=false

images:
  - name: crm
    newName: your-registry.io/crm
    newTag: staging
